import { App, Modal, Notice, Setting, TFile } from "obsidian";
import type LocalOrganizerPlugin from "./main";
import { distillNoteContent } from "./ollama";
import { getCachedVaultContext, getVaultFolders, sanitizeNoteBody } from "./vault-context";
import { organizeFileLocation, updateFrontmatter, updateNoteBody } from "./note-mutator";
import { MIN_CONTENT_CHARS } from "./types";

export class BulkOrganizeModal extends Modal {
  plugin: LocalOrganizerPlugin;
  private selectedFolder: string = "__ALL__";
  private skipOrganized: boolean;
  private autoRename: boolean;
  private autoMove: boolean;
  private isRunning: boolean = false;
  private isCancelled: boolean = false;

  constructor(app: App, plugin: LocalOrganizerPlugin) {
    super(app);
    this.plugin = plugin;
    this.skipOrganized = plugin.settings.skipAlreadyOrganized;
    this.autoRename = plugin.settings.autoRenameFile;
    this.autoMove = plugin.settings.autoMoveToFolder;
  }

  onOpen(): void {
    this.renderInitialView();
  }

  onClose(): void {
    this.isCancelled = true;
    const { contentEl } = this;
    contentEl.empty();
  }

  private renderInitialView(): void {
    const { contentEl } = this;
    contentEl.empty();

    contentEl.createEl("h2", { text: "Bulk Organize Notes & Folders" });
    contentEl.createEl("p", {
      text: "Distill multiple notes sequentially and organize them into relevant folders using your local Ollama instance.",
      cls: "setting-item-description",
    });

    const folders = getVaultFolders(this.app);

    // Folder Scope Setting
    new Setting(contentEl)
      .setName("Scope / Target Folder")
      .setDesc("Choose whether to organize all notes across the entire vault or target a specific folder.")
      .addDropdown((dropdown) => {
        dropdown.addOption("__ALL__", "Entire Vault (All Folders)");
        for (const f of folders) {
          dropdown.addOption(f, f);
        }
        dropdown.setValue(this.selectedFolder);
        dropdown.onChange((val) => {
          this.selectedFolder = val;
        });
      });

    // Skip Already Organized Toggle
    new Setting(contentEl)
      .setName("Skip Already Organized Notes")
      .setDesc("Skip notes that already contain a distilled summary or tasks.")
      .addToggle((toggle) =>
        toggle.setValue(this.skipOrganized).onChange((val) => {
          this.skipOrganized = val;
        })
      );

    // Auto Rename Toggle
    new Setting(contentEl)
      .setName("Rename Notes to AI Topic Title")
      .setDesc("Automatically rename files to the detailed topic title generated by the model.")
      .addToggle((toggle) =>
        toggle.setValue(this.autoRename).onChange((val) => {
          this.autoRename = val;
        })
      );

    // Auto Move Toggle
    new Setting(contentEl)
      .setName("Move Notes to AI-Suggested Folders")
      .setDesc("Automatically relocate notes into matching vault folders based on topic.")
      .addToggle((toggle) =>
        toggle.setValue(this.autoMove).onChange((val) => {
          this.autoMove = val;
        })
      );

    // Action Buttons
    const buttonRow = contentEl.createDiv({ cls: "modal-button-container" });
    buttonRow.style.marginTop = "20px";
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";
    buttonRow.style.gap = "10px";

    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();

    const startBtn = buttonRow.createEl("button", {
      text: "Start Bulk Organizing",
      cls: "mod-cta",
    });
    startBtn.onclick = () => this.startProcessing();
  }

  private async startProcessing(): Promise<void> {
    if (!this.plugin.settings.selectedModel) {
      new Notice("Local Organizer: Please select a model in Settings first.");
      return;
    }

    // 1. Gather candidate files
    let candidateFiles = this.app.vault.getMarkdownFiles().filter((file) => {
      // Exclude hidden folders, trash
      const parts = file.path.split("/");
      return !parts.some((p) => p.startsWith("."));
    });

    if (this.selectedFolder !== "__ALL__") {
      candidateFiles = candidateFiles.filter(
        (f) => f.path.startsWith(this.selectedFolder + "/") || f.parent?.path === this.selectedFolder
      );
    }

    // 2. Filter if skipping already organized
    if (this.skipOrganized) {
      const unorganized: TFile[] = [];
      for (const file of candidateFiles) {
        const content = await this.app.vault.cachedRead(file);
        if (
          !content.includes("> [!abstract] Distilled Summary") &&
          !content.includes("<!-- vault-distiller:summary:start -->")
        ) {
          unorganized.push(file);
        }
      }
      candidateFiles = unorganized;
    }

    if (candidateFiles.length === 0) {
      new Notice("Local Organizer: No eligible unorganized notes found in the selected scope.");
      return;
    }

    // 3. Render Progress View
    this.renderProgressView(candidateFiles);
  }

  private renderProgressView(queue: TFile[]): void {
    const { contentEl } = this;
    contentEl.empty();

    contentEl.createEl("h2", { text: "Bulk Organizing in Progress..." });

    const statusText = contentEl.createEl("p", {
      text: `Preparing to process ${queue.length} note(s)...`,
    });

    const progressBar = contentEl.createEl("progress");
    progressBar.max = queue.length;
    progressBar.value = 0;
    progressBar.style.width = "100%";
    progressBar.style.marginBottom = "15px";

    const logContainer = contentEl.createDiv({
      cls: "vault-distiller-bulk-log",
    });
    logContainer.style.height = "220px";
    logContainer.style.overflowY = "auto";
    logContainer.style.backgroundColor = "var(--background-secondary)";
    logContainer.style.padding = "10px";
    logContainer.style.borderRadius = "6px";
    logContainer.style.fontFamily = "monospace";
    logContainer.style.fontSize = "0.85em";
    logContainer.style.marginBottom = "15px";

    const buttonRow = contentEl.createDiv({ cls: "modal-button-container" });
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";

    const stopBtn = buttonRow.createEl("button", {
      text: "Stop / Cancel",
      cls: "mod-warning",
    });

    stopBtn.onclick = () => {
      this.isCancelled = true;
      stopBtn.disabled = true;
      stopBtn.setText("Stopping...");
    };

    const appendLog = (msg: string) => {
      const line = logContainer.createEl("div", { text: msg });
      line.style.marginBottom = "3px";
      logContainer.scrollTop = logContainer.scrollHeight;
    };

    this.runQueue(queue, progressBar, statusText, appendLog, stopBtn);
  }

  private async runQueue(
    queue: TFile[],
    progressBar: HTMLProgressElement,
    statusText: HTMLParagraphElement,
    appendLog: (msg: string) => void,
    stopBtn: HTMLButtonElement
  ): Promise<void> {
    this.isRunning = true;
    this.isCancelled = false;

    let processedCount = 0;
    let renamedCount = 0;
    let movedCount = 0;

    const validFolders = new Set(getVaultFolders(this.app));

    for (let i = 0; i < queue.length; i++) {
      if (this.isCancelled) {
        appendLog("⏹️ Process stopped by user.");
        break;
      }

      const file = queue[i];
      progressBar.value = i + 1;
      statusText.setText(`[${i + 1}/${queue.length}] Processing "${file.basename}"...`);
      appendLog(`▶ [${i + 1}/${queue.length}] Distilling "${file.basename}"...`);

      try {
        const rawContent = await this.app.vault.cachedRead(file);
        const fileCache = this.app.metadataCache.getFileCache(file);
        const fmOffset = fileCache?.frontmatterPosition?.end?.offset;
        const body = sanitizeNoteBody(rawContent, this.plugin.settings.maxNoteChars, fmOffset);

        if (body.length < MIN_CONTENT_CHARS) {
          appendLog(`   ⚠️ Skipped: body too short (< ${MIN_CONTENT_CHARS} chars).`);
          continue;
        }

        const { tags, titles, titleMap, folders } = getCachedVaultContext(
          this.app,
          file,
          this.plugin.settings.maxContextTags,
          this.plugin.settings.maxContextNotes
        );

        const result = await distillNoteContent(
          this.plugin.settings.ollamaUrl,
          this.plugin.settings.selectedModel,
          this.plugin.settings.temperature,
          file.basename,
          body,
          tags,
          titles,
          folders
        );

        // Safe mutation: frontmatter then body
        const mergedTags = await updateFrontmatter(this.app, file, result, this.plugin.settings);
        await updateNoteBody(this.app, file, result, this.plugin.settings, titleMap, mergedTags);
        processedCount++;

        let logMsg = `   ✅ Distilled & tagged (${result.tags.length} tags)`;

        // Rename and folder relocation
        const orgResult = await organizeFileLocation(
          this.app,
          file,
          result.clean_title,
          result.suggested_folder,
          validFolders,
          this.autoRename,
          this.autoMove
        );

        if (orgResult.renamed) {
          renamedCount++;
          logMsg += ` → 📝 "${orgResult.newTitle}"`;
        }
        if (orgResult.moved) {
          movedCount++;
          logMsg += ` → 📁 "${orgResult.targetFolder}/"`;
        }

        appendLog(logMsg);
      } catch (err) {
        appendLog(`   ❌ Error: ${err instanceof Error ? err.message : String(err)}`);
      }

      // Small pause between notes to yield to event loop and keep GPU cool
      await new Promise((r) => setTimeout(r, 60));
    }

    this.isRunning = false;
    statusText.setText(
      `Finished! Processed ${processedCount} note(s), renamed ${renamedCount}, relocated ${movedCount} to folders.`
    );
    stopBtn.setText("Close");
    stopBtn.className = "mod-cta";
    stopBtn.disabled = false;
    stopBtn.onclick = () => this.close();
  }
}
