import { App, DropdownComponent, Notice, PluginSettingTab, Setting } from "obsidian";
import type LocalOrganizerPlugin from "./main";
import { fetchInstalledModels } from "./ollama";
import { invalidateVaultContextCache } from "./vault-context";
import { SyncConflictModal } from "./sync-conflict-modal";

export class LocalOrganizerSettingTab extends PluginSettingTab {
  plugin: LocalOrganizerPlugin;
  private modelDropdown?: DropdownComponent;

  constructor(app: App, plugin: LocalOrganizerPlugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  async display(): Promise<void> {
    const { containerEl } = this;
    containerEl.empty();

    containerEl.createEl("h2", { text: "Local Vault Organizer Settings" });
    containerEl.createEl("p", {
      text: "Distill notes, extract actionable tasks, and discover vault cross-links using your local Ollama instance completely offline.",
      cls: "setting-item-description",
    });

    // Ollama Server URL
    new Setting(containerEl)
      .setName("Ollama Server URL")
      .setDesc("Base URL where your local Ollama service is listening.")
      .addText((text) =>
        text
          .setPlaceholder("http://127.0.0.1:11434")
          .setValue(this.plugin.settings.ollamaUrl)
          .onChange(async (value) => {
            this.plugin.settings.ollamaUrl = value.trim() || "http://127.0.0.1:11434";
            await this.plugin.saveSettings();
          })
      );

    // Model Selector & Refresh Button
    new Setting(containerEl)
      .setName("Chat Model")
      .setDesc("Select the local model to use for note distillation (e.g., llama3.2:3b, qwen2.5:3b).")
      .addDropdown((dropdown) => {
        this.modelDropdown = dropdown;
        this.rebuildDropdown();
        dropdown.onChange(async (val) => {
          this.plugin.settings.selectedModel = val;
          await this.plugin.saveSettings();
        });
      })
      .addButton((button) =>
        button
          .setButtonText("Fetch / Refresh Models")
          .setCta()
          .onClick(async () => {
            await this.refreshModels(true);
          })
      );

    // Inference Temperature Slider
    new Setting(containerEl)
      .setName("Temperature")
      .setDesc("Controls determinism vs creativity (default 0.2). Lower values produce more structured, consistent output.")
      .addSlider((slider) =>
        slider
          .setLimits(0.0, 1.0, 0.05)
          .setValue(this.plugin.settings.temperature)
          .setDynamicTooltip()
          .onChange(async (val) => {
            this.plugin.settings.temperature = val;
            await this.plugin.saveSettings();
          })
      );

    // Feature Toggles
    containerEl.createEl("h3", { text: "Distillation Output" });

    new Setting(containerEl)
      .setName("Prepend Distilled Summary")
      .setDesc("Add an executive summary callout block at the top of the note body.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.prependSummary)
          .onChange(async (val) => {
            this.plugin.settings.prependSummary = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Append Tasks & Open Questions")
      .setDesc("Append actionable follow-ups and questions as markdown checklist items (- [ ]).")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.appendTodos)
          .onChange(async (val) => {
            this.plugin.settings.appendTodos = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Append Related Notes")
      .setDesc("Append a Related Notes section with wikilinks strictly pointing to existing vault notes.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.appendRelatedLinks)
          .onChange(async (val) => {
            this.plugin.settings.appendRelatedLinks = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Update Title in Frontmatter")
      .setDesc("Inject the model's clean title into YAML frontmatter (title:) if none exists.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.updateFrontmatterTitle)
          .onChange(async (val) => {
            this.plugin.settings.updateFrontmatterTitle = val;
            await this.plugin.saveSettings();
          })
      );

    containerEl.createEl("h3", { text: "Folder Organization & Bulk Processing" });

    new Setting(containerEl)
      .setName("Rename Notes to AI Topic Title")
      .setDesc("Automatically rename note files to the specific, detailed topic title generated by the model.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.autoRenameFile)
          .onChange(async (val) => {
            this.plugin.settings.autoRenameFile = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Move Notes to AI-Suggested Folders")
      .setDesc("Relocate notes into matching vault folders based on topic content.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.autoMoveToFolder)
          .onChange(async (val) => {
            this.plugin.settings.autoMoveToFolder = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Skip Already Organized Notes in Bulk Runs")
      .setDesc("Ignore notes that already contain a distilled summary or tasks.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.skipAlreadyOrganized)
          .onChange(async (val) => {
            this.plugin.settings.skipAlreadyOrganized = val;
            await this.plugin.saveSettings();
          })
      );

    containerEl.createEl("h3", { text: "Sync Conflicts (Syncthing / Obsidian Sync)" });

    new Setting(containerEl)
      .setName("Auto-Scan for Sync Conflicts on Startup")
      .setDesc("Detect and notify when Syncthing conflict files (e.g. .sync-conflict-...) appear in the vault.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.autoScanSyncConflicts)
          .onChange(async (val) => {
            this.plugin.settings.autoScanSyncConflicts = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Scan & Resolve Sync Conflicts Now")
      .setDesc("Scan the entire vault for sync conflict files, merge additions into canonical notes, and move conflict files to trash.")
      .addButton((button) =>
        button
          .setButtonText("Scan & Resolve Conflicts")
          .setCta()
          .onClick(() => {
            new SyncConflictModal(this.app, this.plugin).open();
          })
      );

    containerEl.createEl("h3", { text: "Concept Discovery & Reference Primers" });

    new Setting(containerEl)
      .setName("Auto-Discover Novel Concepts")
      .setDesc("Prompt to research and generate reference primers when novel technical concepts or tools are detected in notes.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.autoDiscoverConcepts)
          .onChange(async (val) => {
            this.plugin.settings.autoDiscoverConcepts = val;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Default Concept Notes Folder")
      .setDesc("Target folder where new concept primers will be created (e.g. Computer Science, Concepts). Created automatically if it does not exist.")
      .addText((text) =>
        text
          .setPlaceholder("Computer Science")
          .setValue(this.plugin.settings.defaultConceptFolder || "Computer Science")
          .onChange(async (val) => {
            this.plugin.settings.defaultConceptFolder = val.trim();
            await this.plugin.saveSettings();
          })
      );

    // Advanced Context Limits (RTX 3060 6GB)
    containerEl.createEl("h3", { text: "Context Window Limits (RTX 3060 6GB VRAM)" });

    new Setting(containerEl)
      .setName("Max Vault Tags in Context")
      .setDesc("Number of most frequent vault tags sent to LLM for taxonomy guidance.")
      .addText((text) =>
        text
          .setValue(String(this.plugin.settings.maxContextTags))
          .onChange(async (val) => {
            const num = parseInt(val, 10);
            if (!isNaN(num) && num > 0) {
              this.plugin.settings.maxContextTags = num;
              invalidateVaultContextCache();
              await this.plugin.saveSettings();
            }
          })
      );

    new Setting(containerEl)
      .setName("Max Vault Notes in Context")
      .setDesc("Number of hub notes (ranked by backlinks & recency) sent to LLM for link suggestions.")
      .addText((text) =>
        text
          .setValue(String(this.plugin.settings.maxContextNotes))
          .onChange(async (val) => {
            const num = parseInt(val, 10);
            if (!isNaN(num) && num > 0) {
              this.plugin.settings.maxContextNotes = num;
              invalidateVaultContextCache();
              await this.plugin.saveSettings();
            }
          })
      );

    new Setting(containerEl)
      .setName("Max Note Body Characters")
      .setDesc("Note content character limit sent to Ollama (default 16000 chars ≈ 4000 tokens).")
      .addText((text) =>
        text
          .setValue(String(this.plugin.settings.maxNoteChars))
          .onChange(async (val) => {
            const num = parseInt(val, 10);
            if (!isNaN(num) && num > 0) {
              this.plugin.settings.maxNoteChars = num;
              await this.plugin.saveSettings();
            }
          })
      );

    // Auto-fetch models in the background on settings open
    this.refreshModels(false);
  }

  private rebuildDropdown(): void {
    if (!this.modelDropdown) return;
    this.modelDropdown.selectEl.empty();

    const models = this.plugin.settings.availableModels;
    if (!models || models.length === 0) {
      this.modelDropdown.addOption("", "(Click 'Fetch Models' to populate)");
    } else {
      for (const m of models) {
        this.modelDropdown.addOption(m, m);
      }
    }

    const defaultModel =
      models.find((m) => m.includes("llama3.2") || m.includes("qwen")) || models[0] || "";

    if (this.plugin.settings.selectedModel && models.includes(this.plugin.settings.selectedModel)) {
      this.modelDropdown.setValue(this.plugin.settings.selectedModel);
    } else if (defaultModel) {
      this.modelDropdown.setValue(defaultModel);
      this.plugin.settings.selectedModel = defaultModel;
      this.plugin.saveSettings();
    }
  }

  private async refreshModels(showUserNotice: boolean): Promise<void> {
    try {
      const models = await fetchInstalledModels(this.plugin.settings.ollamaUrl);
      this.plugin.settings.availableModels = models;
      if (!this.plugin.settings.selectedModel || !models.includes(this.plugin.settings.selectedModel)) {
        const preferred =
          models.find((m) => m.includes("llama3.2") || m.includes("qwen")) || models[0] || "";
        this.plugin.settings.selectedModel = preferred;
      }
      await this.plugin.saveSettings();
      this.rebuildDropdown();
      if (showUserNotice) {
        new Notice(`Local Organizer: Found ${models.length} installed model(s).`);
      }
    } catch {
      if (showUserNotice) {
        new Notice(
          `Local Organizer: Could not reach Ollama at ${this.plugin.settings.ollamaUrl}. Make sure Ollama is running.`
        );
      }
    }
  }
}
