import { App, Modal, Notice, Setting } from "obsidian";
import type LocalOrganizerPlugin from "./main";
import {
  resolveConflictPair,
  scanVaultForSyncConflicts,
} from "./sync-conflict-merger";
import { SyncConflictPair } from "./types";

interface ConflictItemState {
  pair: SyncConflictPair;
  selected: boolean;
}

/**
 * Interactive review and batch merge modal for Syncthing / Obsidian sync conflict files.
 */
export class SyncConflictModal extends Modal {
  plugin: LocalOrganizerPlugin;
  private items: ConflictItemState[] = [];
  private isRunning: boolean = false;
  private isCancelled: boolean = false;

  constructor(app: App, plugin: LocalOrganizerPlugin) {
    super(app);
    this.plugin = plugin;
  }

  onOpen(): void {
    this.scanAndRender();
  }

  onClose(): void {
    this.isCancelled = true;
    const { contentEl } = this;
    contentEl.empty();
  }

  private scanAndRender(): void {
    const { contentEl } = this;
    contentEl.empty();

    const pairs = scanVaultForSyncConflicts(this.app);
    this.items = pairs.map((pair) => ({ pair, selected: true }));

    contentEl.createEl("h2", { text: "Sync Conflict Resolver & Merger" });

    if (this.items.length === 0) {
      contentEl.createEl("p", {
        text: "✨ No sync conflict files found in your vault! Everything is in sync.",
        cls: "setting-item-description",
      });

      const closeContainer = contentEl.createDiv({ cls: "modal-button-container" });
      closeContainer.style.marginTop = "20px";
      const closeBtn = closeContainer.createEl("button", { text: "Close", cls: "mod-cta" });
      closeBtn.onclick = () => this.close();
      return;
    }

    contentEl.createEl("p", {
      text: `Found ${this.items.length} sync conflict file(s) generated by Syncthing or cloud sync. Select the files you want to merge into their canonical counterparts:`,
      cls: "setting-item-description",
    });

    // Conflict list
    const listContainer = contentEl.createDiv({ cls: "vault-distiller-conflict-list" });
    listContainer.style.maxHeight = "360px";
    listContainer.style.overflowY = "auto";
    listContainer.style.marginBottom = "15px";
    listContainer.style.display = "flex";
    listContainer.style.flexDirection = "column";
    listContainer.style.gap = "10px";

    for (const item of this.items) {
      const card = listContainer.createDiv({ cls: "vault-distiller-conflict-card" });
      card.style.border = "1px solid var(--background-modifier-border)";
      card.style.borderRadius = "8px";
      card.style.padding = "10px 14px";
      card.style.backgroundColor = "var(--background-secondary)";

      // Top row: Checkbox + Conflict file path
      const topRow = card.createDiv();
      topRow.style.display = "flex";
      topRow.style.alignItems = "center";
      topRow.style.gap = "10px";
      topRow.style.marginBottom = "4px";

      const cb = topRow.createEl("input", { type: "checkbox" });
      cb.checked = item.selected;
      cb.onchange = () => {
        item.selected = cb.checked;
        updateButtons();
      };

      const nameEl = topRow.createEl("span", { text: item.pair.conflictFile.path });
      nameEl.style.fontWeight = "600";
      nameEl.style.fontSize = "0.95em";
      nameEl.style.wordBreak = "break-all";

      // Target row
      const targetRow = card.createDiv();
      targetRow.style.fontSize = "0.85em";
      targetRow.style.color = "var(--text-muted)";
      targetRow.style.marginLeft = "26px";

      if (item.pair.canonicalFile) {
        if (item.pair.isOrphaned) {
          targetRow.setText(`↳ 🔄 Relocated target: [[${item.pair.canonicalFile.path}]]`);
        } else {
          targetRow.setText(`↳ 📝 Merges into: [[${item.pair.canonicalFile.path}]]`);
        }
      } else {
        targetRow.setText(`↳ 📁 Orphaned conflict: Will restore as "${item.pair.canonicalPath}"`);
      }
    }

    // Action button container
    const buttonRow = contentEl.createDiv({ cls: "modal-button-container" });
    buttonRow.style.marginTop = "15px";
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "space-between";
    buttonRow.style.alignItems = "center";

    const leftGroup = buttonRow.createDiv();
    const selectAllBtn = leftGroup.createEl("button", { text: "Select All" });
    selectAllBtn.style.marginRight = "6px";
    selectAllBtn.onclick = () => {
      this.items.forEach((i) => (i.selected = true));
      this.scanAndRender();
    };

    const deselectBtn = leftGroup.createEl("button", { text: "Deselect All" });
    deselectBtn.onclick = () => {
      this.items.forEach((i) => (i.selected = false));
      this.scanAndRender();
    };

    const rightGroup = buttonRow.createDiv();
    rightGroup.style.display = "flex";
    rightGroup.style.gap = "10px";

    const cancelBtn = rightGroup.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();

    const mergeBtn = rightGroup.createEl("button", {
      text: "Merge & Clean Conflicts",
      cls: "mod-cta",
    });

    const updateButtons = () => {
      const selectedCount = this.items.filter((i) => i.selected).length;
      mergeBtn.disabled = selectedCount === 0;
      mergeBtn.setText(`Merge & Clean (${selectedCount})`);
    };
    updateButtons();

    mergeBtn.onclick = () => {
      const selected = this.items.filter((i) => i.selected).map((i) => i.pair);
      if (selected.length === 0) return;
      this.renderProgressView(selected);
    };
  }

  private renderProgressView(queue: SyncConflictPair[]): void {
    const { contentEl } = this;
    contentEl.empty();

    contentEl.createEl("h2", { text: "Merging Sync Conflicts" });

    const statusText = contentEl.createEl("p", {
      text: `Processing 0 of ${queue.length}...`,
      cls: "setting-item-description",
    });

    const progressBar = contentEl.createEl("progress");
    progressBar.max = queue.length;
    progressBar.value = 0;
    progressBar.style.width = "100%";
    progressBar.style.marginBottom = "15px";

    const logContainer = contentEl.createDiv({ cls: "vault-distiller-log-container" });
    logContainer.style.maxHeight = "260px";
    logContainer.style.overflowY = "auto";
    logContainer.style.padding = "10px";
    logContainer.style.backgroundColor = "var(--background-secondary)";
    logContainer.style.border = "1px solid var(--background-modifier-border)";
    logContainer.style.borderRadius = "6px";
    logContainer.style.fontFamily = "var(--font-monospace)";
    logContainer.style.fontSize = "0.85em";
    logContainer.style.lineHeight = "1.5";
    logContainer.style.marginBottom = "20px";

    const buttonRow = contentEl.createDiv({ cls: "modal-button-container" });
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";

    const stopBtn = buttonRow.createEl("button", { text: "Stop" });
    stopBtn.onclick = () => {
      this.isCancelled = true;
      stopBtn.disabled = true;
      stopBtn.setText("Stopping...");
    };

    const appendLog = (msg: string) => {
      const line = logContainer.createEl("div", { text: msg });
      line.style.marginBottom = "3px";
      logContainer.scrollTop = logContainer.scrollHeight;
    };

    this.runQueue(queue, progressBar, statusText, appendLog, stopBtn);
  }

  private async runQueue(
    queue: SyncConflictPair[],
    progressBar: HTMLProgressElement,
    statusText: HTMLParagraphElement,
    appendLog: (msg: string) => void,
    stopBtn: HTMLButtonElement
  ): Promise<void> {
    this.isRunning = true;
    this.isCancelled = false;
    let successCount = 0;
    let failedCount = 0;

    for (let i = 0; i < queue.length; i++) {
      if (this.isCancelled) {
        appendLog("⏹️ Process stopped by user.");
        break;
      }

      const pair = queue[i];
      progressBar.value = i + 1;
      statusText.setText(`[${i + 1}/${queue.length}] Merging "${pair.conflictFile.name}"...`);
      appendLog(`▶ [${i + 1}/${queue.length}] Resolving: ${pair.conflictFile.path}`);

      try {
        const result = await resolveConflictPair(this.app, pair);
        successCount++;
        appendLog(`   ✅ ${result.message}`);
      } catch (err) {
        failedCount++;
        const msg = err instanceof Error ? err.message : String(err);
        appendLog(`   ❌ Error: ${msg}`);
      }
    }

    this.isRunning = false;
    statusText.setText(`Finished! Successfully resolved ${successCount} conflict(s). ${failedCount > 0 ? `(${failedCount} failed)` : ""}`);
    stopBtn.setText("Done");
    stopBtn.className = "mod-cta";
    stopBtn.disabled = false;
    stopBtn.onclick = () => this.close();
    new Notice(`Local Organizer: Resolved ${successCount} sync conflict file(s).`);
  }
}
