import { App, TFile } from "obsidian";
import { SyncConflictPair } from "./types";

export interface ParsedConflictFilename {
  baseName: string;
  extension: string;
}

/**
 * Recognizes standard sync conflict patterns generated by Syncthing,
 * Obsidian Sync, Nextcloud, Dropbox, and OneDrive.
 * e.g., "Life List.sync-conflict-20261004-105832-MG5Q4E5.md" -> "Life List.md"
 */
export function parseSyncConflictFilename(filename: string): ParsedConflictFilename | null {
  const match = filename.match(
    /^(.+?)(?:\.sync-conflict-\d{8}-\d{6}-[A-Za-z0-9]+|\s*\((?:conflicted copy|conflict)[^)]*\)|\.conflict-[A-Za-z0-9_-]+)(\.[^.]+)$/i
  );
  if (match) {
    return {
      baseName: match[1].trim(),
      extension: match[2].trim(),
    };
  }
  return null;
}

/**
 * Finds the canonical file corresponding to a sync conflict file.
 * First checks co-located in the same folder. If not found (e.g. Canonical was moved),
 * searches the entire vault for the canonical baseName.
 */
export function findCanonicalFile(app: App, conflictFile: TFile): { canonical: TFile | null; isOrphaned: boolean; canonicalPath: string } {
  const parsed = parseSyncConflictFilename(conflictFile.name);
  if (!parsed) {
    return { canonical: null, isOrphaned: false, canonicalPath: "" };
  }

  const canonicalName = `${parsed.baseName}${parsed.extension}`;
  const parentPath = conflictFile.parent ? conflictFile.parent.path.replace(/^\/+|\/+$/g, "") : "";
  const coLocatedPath = parentPath ? `${parentPath}/${canonicalName}` : canonicalName;

  // 1. Check co-located file
  const coLocated = app.vault.getAbstractFileByPath(coLocatedPath);
  if (coLocated instanceof TFile) {
    return { canonical: coLocated, isOrphaned: false, canonicalPath: coLocatedPath };
  }

  // 2. Search entire vault for a markdown file with the matching basename
  const allMarkdown = app.vault.getMarkdownFiles();
  const targetLower = parsed.baseName.toLowerCase();

  const vaultMatch = allMarkdown.find((f) => {
    if (f.path === conflictFile.path) return false;
    if (parseSyncConflictFilename(f.name)) return false;
    return f.basename.toLowerCase() === targetLower;
  });

  if (vaultMatch) {
    return { canonical: vaultMatch, isOrphaned: true, canonicalPath: vaultMatch.path };
  }

  return { canonical: null, isOrphaned: true, canonicalPath: coLocatedPath };
}

/**
 * Scans the vault for any markdown sync conflict files.
 */
export function scanVaultForSyncConflicts(app: App): SyncConflictPair[] {
  const allFiles = app.vault.getMarkdownFiles();
  const pairs: SyncConflictPair[] = [];

  for (const file of allFiles) {
    const parsed = parseSyncConflictFilename(file.name);
    if (parsed) {
      const { canonical, isOrphaned, canonicalPath } = findCanonicalFile(app, file);
      pairs.push({
        conflictFile: file,
        canonicalFile: canonical,
        canonicalPath,
        isOrphaned,
        status: "pending",
      });
    }
  }

  // Sort by folder and name
  pairs.sort((a, b) => a.conflictFile.path.localeCompare(b.conflictFile.path));
  return pairs;
}

interface MarkdownSection {
  heading: string;
  lines: string[];
}

/**
 * Parses markdown into structured sections bounded by headings (#, ##, ###) or dividers (---).
 */
function parseMarkdownSections(content: string): MarkdownSection[] {
  const lines = content.split(/\r?\n/);
  const sections: MarkdownSection[] = [];
  let currentHeading = "";
  let currentLines: string[] = [];

  for (const line of lines) {
    if (line.match(/^#{1,6}\s+/)) {
      if (currentLines.length > 0 || currentHeading !== "") {
        sections.push({ heading: currentHeading, lines: currentLines });
      }
      currentHeading = line;
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }
  sections.push({ heading: currentHeading, lines: currentLines });
  return sections;
}

/**
 * Losslessly merges lines within a section:
 * - Unifies checklist items (- [ ] / - [x]), preferring - [x] if completed in either file.
 * - Appends unique checklist tasks and unique bullet points/paragraphs from the conflict file.
 */
function mergeSectionLines(canonicalLines: string[], conflictLines: string[]): string[] {
  const result = [...canonicalLines];

  // Map of canonical checklist items
  const itemMap = new Map<string, { index: number; checked: boolean; raw: string }>();

  for (let i = 0; i < result.length; i++) {
    const m = result[i].match(/^(\s*[-*]\s*\[)([ xX])(\]\s*)(.*)$/);
    if (m) {
      const cleanText = m[4].trim().toLowerCase();
      itemMap.set(cleanText, {
        index: i,
        checked: m[2].toLowerCase() === "x",
        raw: result[i],
      });
    }
  }

  for (const line of conflictLines) {
    const m = line.match(/^(\s*[-*]\s*\[)([ xX])(\]\s*)(.*)$/);
    if (m) {
      const cleanText = m[4].trim().toLowerCase();
      const isChecked = m[2].toLowerCase() === "x";
      if (itemMap.has(cleanText)) {
        const existing = itemMap.get(cleanText)!;
        // Upgrade to checked if checked on either device
        if (isChecked && !existing.checked) {
          result[existing.index] = line;
          itemMap.set(cleanText, { index: existing.index, checked: true, raw: line });
        }
      } else {
        // New item from conflict! Add it
        result.push(line);
        itemMap.set(cleanText, { index: result.length - 1, checked: isChecked, raw: line });
      }
    } else {
      // Normal bullet or text line
      const trimmed = line.trim();
      if (trimmed && trimmed !== "---") {
        const exists = result.some((r) => r.trim() === trimmed);
        if (!exists) {
          result.push(line);
        }
      }
    }
  }

  return result;
}

/**
 * Intelligently merges a canonical note and a sync-conflict note:
 * 1. Preserves frontmatter block from canonical note (incorporating unique conflict keys).
 * 2. Unions checklists (preserving completion states).
 * 3. Incorporates unique sections/ideas from the conflict note.
 * 4. Consolidates tags at the very bottom preceded by '---'.
 */
export function smartMergeNotes(canonicalContent: string, conflictContent: string): string {
  // If identical, return canonical directly
  if (canonicalContent.trim() === conflictContent.trim()) {
    return canonicalContent;
  }

  // 1. Separate frontmatter from body
  let canonicalFm = "";
  let canonicalBody = canonicalContent;
  if (canonicalContent.startsWith("---")) {
    const closingIdx = canonicalContent.indexOf("\n---", 3);
    if (closingIdx !== -1) {
      canonicalFm = canonicalContent.slice(0, closingIdx + 4) + "\n\n";
      canonicalBody = canonicalContent.slice(closingIdx + 4).trim();
    }
  }

  let conflictBody = conflictContent;
  if (conflictContent.startsWith("---")) {
    const closingIdx = conflictContent.indexOf("\n---", 3);
    if (closingIdx !== -1) {
      conflictBody = conflictContent.slice(closingIdx + 4).trim();
    }
  }

  // 2. Extract all tags across both files to unify at end
  const tagSet = new Set<string>();
  const tagRegex = /#([a-zA-Z0-9_\-/]+)/g;
  let match;
  while ((match = tagRegex.exec(canonicalContent)) !== null) {
    tagSet.add(match[1].toLowerCase());
  }
  while ((match = tagRegex.exec(conflictContent)) !== null) {
    tagSet.add(match[1].toLowerCase());
  }

  // Strip existing trailing tag lines from both bodies
  canonicalBody = canonicalBody
    .replace(/(?:\r?\n---\s*)+\r?\n(?:#[a-zA-Z0-9_\-/]+[\t ]*(?:\r?\n)?)+(?=\r?\n|$)/g, "")
    .trim();
  conflictBody = conflictBody
    .replace(/(?:\r?\n---\s*)+\r?\n(?:#[a-zA-Z0-9_\-/]+[\t ]*(?:\r?\n)?)+(?=\r?\n|$)/g, "")
    .trim();

  // 3. Section-aware merge
  const secA = parseMarkdownSections(canonicalBody);
  const secB = parseMarkdownSections(conflictBody);

  const secBMap = new Map<string, MarkdownSection>();
  for (const s of secB) {
    const key = s.heading.trim().toLowerCase();
    secBMap.set(key, s);
  }

  const mergedSections: MarkdownSection[] = [];
  for (const sA of secA) {
    const key = sA.heading.trim().toLowerCase();
    const matchB = secBMap.get(key);
    if (matchB) {
      const mergedLines = mergeSectionLines(sA.lines, matchB.lines);
      mergedSections.push({ heading: sA.heading, lines: mergedLines });
      secBMap.delete(key);
    } else {
      mergedSections.push(sA);
    }
  }

  // Append any sections that only existed in conflict file
  for (const [_, sB] of secBMap) {
    if (sB.heading || sB.lines.some((l) => l.trim().length > 0)) {
      mergedSections.push(sB);
    }
  }

  // 4. Assemble merged body
  const assembledLines: string[] = [];
  for (const s of mergedSections) {
    if (s.heading) {
      assembledLines.push(s.heading);
    }
    assembledLines.push(...s.lines);
  }

  let finalBody = assembledLines.join("\n").trim();

  // Clean stray dividers between checklist items and ensure single clean divider before headings
  finalBody = finalBody.replace(/(?:\r?\n---\s*)+\r?\n(?=\s*[-*]\s*\[)/g, "\n");
  finalBody = finalBody.replace(/(?:\s*\r?\n)*\s*(?:---\s*)?\r?\n(#{1,6}\s+[^\n]+)/g, "\n\n---\n$1");

  // 5. Append consolidated tags at the very bottom
  if (tagSet.size > 0) {
    const tagLine = Array.from(tagSet)
      .map((t) => `#${t}`)
      .join(" ");
    finalBody = finalBody.trim() + `\n\n---\n${tagLine}\n`;
  }

  return (canonicalFm + finalBody).trim() + "\n";
}

export interface ConflictResolutionResult {
  conflictPath: string;
  canonicalPath: string;
  actionTaken: "merged_and_trashed" | "renamed_orphan" | "trashed_identical";
  message: string;
}

/**
 * Resolves a single conflict pair:
 * - If canonical file exists, merges content and trashes the conflict file.
 * - If conflict is an orphan (canonical doesn't exist anywhere), renames conflict file to canonical.
 * - Uses app.vault.trash for safe rollback.
 */
export async function resolveConflictPair(
  app: App,
  pair: SyncConflictPair
): Promise<ConflictResolutionResult> {
  const { conflictFile, canonicalFile, canonicalPath, isOrphaned } = pair;

  // Case 1: Canonical file exists (co-located or relocated)
  if (canonicalFile) {
    const canonicalContent = await app.vault.read(canonicalFile);
    const conflictContent = await app.vault.read(conflictFile);

    if (canonicalContent.trim() === conflictContent.trim()) {
      // Identical file: safely trash the duplicate conflict file
      await app.vault.trash(conflictFile, true);
      return {
        conflictPath: conflictFile.path,
        canonicalPath: canonicalFile.path,
        actionTaken: "trashed_identical",
        message: `Identical content; safely trashed duplicate conflict file.`,
      };
    }

    // Merge contents
    const merged = smartMergeNotes(canonicalContent, conflictContent);

    // Update canonical file atomically
    await app.vault.modify(canonicalFile, merged);

    // Safely trash conflict file
    await app.vault.trash(conflictFile, true);

    return {
      conflictPath: conflictFile.path,
      canonicalPath: canonicalFile.path,
      actionTaken: "merged_and_trashed",
      message: `Successfully merged additions and checklists into "${canonicalFile.path}". Conflict file moved to trash.`,
    };
  }

  // Case 2: Orphaned conflict file (canonical file does not exist anywhere in the vault)
  // Safely rename conflict file by removing the .sync-conflict suffix
  if (isOrphaned && !app.vault.getAbstractFileByPath(canonicalPath)) {
    await app.fileManager.renameFile(conflictFile, canonicalPath);
    return {
      conflictPath: conflictFile.path,
      canonicalPath,
      actionTaken: "renamed_orphan",
      message: `No existing canonical file found; restored conflict file as "${canonicalPath}".`,
    };
  }

  throw new Error(`Unable to resolve conflict: target path "${canonicalPath}" already occupied or invalid.`);
}
